### ISSUE TITLE
Generating automated primary keys

### ISSUE THREAD

**Issue by terazus** [Zendro-dev/ISA-plug-and-play-warehouse#3]
Hello :)
I've started playing with both the PSQL and graphQL servers and i'm really enjoying it.
However, i'm encountering a difficult step that could be automated. It happens on creation.

An example to create a comment with a mutation:
```gql
mutation createComment {
  addComment(id: 1, name: "comment Test") {
    name
    id
  }
}
```
Now, if the id is already being used, it throws an error. Makes sense if the ID wasn't required and could be automatically generated to provide this graphQL mutation:
```gql
mutation createComment {
  addComment(name: "comment Test") {
    name
    id
  }
}
```

To solve this issue, this is what i've done:
1 - Alter the database tables so that the ID becomes a serial. However, this can only be done at creation since serials aren't proper data types. The alternative is to use the full command:
```psql
CREATE SEQUENCE id_serial AS integer START 1 OWNED BY comments.id;
ALTER TABLE comments ALTER COLUMN id SET DEFAULT nextval('id_serial');
```
This is what the table looks like after altering: 
![image](https://user-images.githubusercontent.com/6538906/156564755-1b21374e-76d7-4951-8428-b1be445fbb7c.png)
2 - Change the graph schema definition on the addComment mutation so that ID is not required anymore `addComment(id: ID, ...)`
3 - Finally remove the id attribute from the `/model/sql/comment.js` file at the level of the class that extends `Sequelize.Model`.

This is what I get once done:
![image](https://user-images.githubusercontent.com/6538906/156564423-3a976f37-7e85-45a8-a0bf-e52ca3b8fee8.png)
For the comment creation.
And now i can bind that comment to another object:
![image](https://user-images.githubusercontent.com/6538906/156564524-57ee6b15-8502-4c3e-be80-c9bfddc64258.png)

Now I'm wondering if this is something that could be implemented directly into zendro ? If not I can make some sort of patch that I can reapply in case we need to re-pull the code from the source.

You let me know what you think :)

Thx !

**Comment by coeit** [comment]
Zendro actually has support for integer sequence primary key attributes. If in the model definition JSON there is no specific attribute delared as `internalId` an `id` field is automatically added that uses a sequence to assign numeric ascending ids to records created (very similiar to what you did manually here).

We chose to use manual String primary keys in this case because that way we can guarantee uniqueness even for distributed setups where data might come from different servers / databases.

**Comment by terazus** [comment]
I'm closing the issue then. It could be nice if you could show me how to do this at some point :)
